name: Check connection to VM

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checks out the repository code

      - name: Set up SSH Keys
        run: |
          mkdir -p ~/.ssh
          cp student-admin_key.pem ~/.ssh/student-admin_key.pem 
          chmod 600 ~/.ssh/student-admin_key.pem  

      - name: Add VM to SSH known hosts
        run: |
          ssh-keyscan -H 3.142.84.124 >> ~/.ssh/known_hosts 

      - name: Check SSH connection
        run: |
          ssh -i ~/.ssh/student-admin_key.pem ec2-user@3.142.84.124 "echo 'Successfully connected!'"
